security:
    encoders:
        App\Entity\User:
            # Use native password encoder
            # This value auto-selects the best possible hashing algorithm
            # (i.e. Sodium when available).
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    enable_authenticator_manager: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            anonymous: false
            lazy: true
            provider: app_user_provider
#            form_login:
#                login_path: login #//login
#                check_path: login #//login
#            entry_point: App_login #//login
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: ROLE_USER  }
        - { path: ^/app_homepage, roles: ROLE_USER  }
        - { path: ^/app_question_show, roles: ROLE_USER  }
        - { path: ^/app_answer_vote, roles: ROLE_USER  }
        - { path: ^/manage/users, roles: ROLE_USER  }
        - #        - { path: ^/admin, roles: ROLE_ADMIN }
          #        - - { path: ^/profile, roles: ROLE_USER }

#        roles:
#            ROLE_USER:        [ROLE_DEFAULT] # ROLE_USER implies ROLE_DEFAULT
#            ROLE_ADMIN:       [ROLE_USER] # ROLE_ADMIN implies ROLE_USER
#            ROLE_SUPER_ADMIN: [ROLE_ADMIN]



